### ISSUE TITLE
Object Data Iteration?

### ISSUE THREAD

**Issue by Jackoz530** [rcorre/dtiled#7]
EDIT 1: I accidentally sent it with no message.
EDIT 2: Just now I realized as I was reading the documentation, the .layers property of MapData gets tiles AND objects. I am now going to try it. 
EDIT 3: I tried to access the object layer and the objects by extracting it from the MapData. Range Violation still stands. I'm guessing I'm accessing the wrong element.

Hello, it's me again. 
So I was trying to iterate through the Object Layer of a specific Layer and I could not find any object layers. 

I first loaded the "FeatureLayer" and procured the objects from it. 
Then I stored the objects to a global ObjectData[] variable.
Then I started to iterate it using a for loop and the program spew Range Violations, stating that there was nothing in it. The for loop started with 0.

When will the loop start?
and how does one Iterate to the Object layer?

My tiled setup is as follows:
![tiled_object](https://cloud.githubusercontent.com/assets/10094438/11530785/77fdc40e-9932-11e5-996f-4f83ea1c94d5.png)

And here is the error along with the for loop that is having violations on
![vs_range](https://cloud.githubusercontent.com/assets/10094438/11530928/ac08f402-9933-11e5-9918-216bf96b0ac7.png)

**Comment by rcorre** [comment]
Its hard to tell without seeing some code and the map data, but here's a little explanation:

Any given layer is _either_ an object or a tile layer. A tile layer has its `data` field populated but `objects` is empty. An object layer has entries in its `objects` field but its `data` field is empty (though it looks like you may not have placed any objects in your layer called "objects").

So, assuming you do have some objects in that layer, you can inspect them with: `mapData.getLayer("objects").objects`.

Here's an [example](https://github.com/rcorre/damage_control/blob/master/src/battle/entities/tilemap.d#L83-L99) from the game I'm currently working on.

First I load the terrain from a layer called "ground".
Then I inspect the `objects` in the "reactors" layer. This layer contains a number of rectangles, each of which represents a reactor location. I use the x,y coordinates to determine which tile to place it at (you can ignore the -1, thats just because a reactor takes up multiple tiles and is placed at a grid intersection).

Note that the (x,y) coords of an object are pixels, _not_ `RowCols`, because objects don't have to fit nicely into the grid (unlike tiles).

**Comment by Jackoz530** [comment]
> Note that the (x,y) coords of an object are pixels, not RowCols, because objects don't have to fit nicely >into the grid (unlike tiles).

So are the objects already loaded and set into the specific tiles where I placed them into using Tiled, 
or will I need to set the objects manually into their respective tiles?

> Its hard to tell without seeing some code and the map data

The sample code is this:

> ```
>     foreach(rect; object_list[name].object_)
>     {
>         auto coord = RowCol(rect.y / 32, rect.x / 32);
>         auto post = map_list[name].tileOffset(coord.south.east).as!Vector2f;
> ```

```
    }
```

The map_list is a container for tilemaps.

This is the map data:

[sample.txt](https://github.com/rcorre/dtiled/files/50758/sample.txt)

**Comment by rcorre** [comment]
> So are the objects already loaded and set into the specific tiles where I placed them into using Tiled, 
> or will I need to set the objects manually into their respective tiles?

Neither tiled nor dtiled have a concept of what a tile _is_ within your game.
That's why a map is defined as an `OrthoMap!T` -- `T` just some type containing whatever _you_ want in a tile.

Looking at your example, your layer named "objects" contains two rectangles.
If you inspect `mapData.getLayer("objects").objects`, you will find two rectangles an can read their x, y, width, height, properties, ect.

What you actually do with that information is up to you.

For example, maybe you're using rectangles to label 'unreachable' areas of the map. 
You could handle this by giving your `Tile` type an `impassable` field.
When loading the map, you'd inspect `mapData.getLayer("barriers").objects`, where you'd placed a bunch of rects to mark unreachable areas.
For each rect, you'd figure out which tiles it covered and set their `impassable` property to `true`.

Again, that's just one of countless examples.
Tiled tries not to assume too much about your game.
Its just an easy way to organize information that you are free to interpret as you with.

**Comment by Jackoz530** [comment]
> If you inspect mapData.getLayer("objects").objects, you will find two rectangles an can read their x, y, width, height, properties, ect.

Ohh now I get it. Sorry if I've been a bit slow.
So the objects contains whatever shape you put it there while creating the Objects in Tiled, and you manipulate the Shapes INSIDE the object not the objects itself.

So for a simple collision detection all I got to do is to:

auto rect = mapData.getLayer("objects").objects;

Then extract the data from said Rect over a loop then test it for collision.

**Comment by rcorre** [comment]
Assuming you meant rect**s** and not rect, then yes.

`mapData.getLayer("objects").objects` will return a range of rects, not just one.

> Ohh now I get it. Sorry if I've been a bit slow.

No worries, like I said, this helps me think about how I could document better :)

**Comment by Jackoz530** [comment]
Sorry If I'm too annoying but when I tried to access the .height field, it still spew down the Range violation error:

>   bool checkCollidedTerrain(Sprite sprite, string name)
>     {  
>         foreach(rect; object_list[name].object_)
>         {
>             auto coord = rect.height;
>         }
>         return false;
>     }

I used these as a wrapper for storing the objects:

>   private Object_Layer_Data[string] object_list;

```
struct Object_Layer_Data
{
    ObjectData[] object_;
}
```

and I did insert it into the struct: 

> object_list[name] = Object_Layer_Data(data.getLayer("object").objects);

Error is seen here:

![vs_range](https://cloud.githubusercontent.com/assets/10094438/11530928/ac08f402-9933-11e5-9918-216bf96b0ac7.png)

**Comment by rcorre** [comment]
`for (int counter = 0 ; counter <= someArray.length ; counter++)`

The last iteration will try to access `someArray[someArray.length]`, which is out of bounds (the last element is `someArray[someArray.length-1]`).

You want:
`for (int counter = 0 ; counter < someArray.length ; counter++)`

Or, even better:
`foreach (counter, element ; someArray)`

Much harder to hit off-by-one errors that way :)

**Comment by rcorre** [comment]
Actually, you're not even using the counter, so just:

`foreach (element ; someArray)`

**Comment by Jackoz530** [comment]
for (int counter = 0 ; counter <= someArray.length ; counter++)

The last iteration will try to access someArray[someArray.length], which is out of bounds (the last element is someArray[someArray.length-1]).

You want:
for (int counter = 0 ; counter < someArray.length ; counter++)

Or, even better:
foreach (counter, element ; someArray)

Much harder to hit off-by-one errors that way :)

Well I have been using "foreach" after you're advice, and I've been using that screenshot to just refer to the error. It's just that the error is the same, switching from to for loops and foreach didn't help.

The current code is this, specifically starting at line 138:

> ```
> bool checkCollidedTerrain(Sprite sprite, string name)
> {   
>     foreach(rect; object_list[name].object_)
>     {
>         auto coord = rect.height;
>     }
>     return false;
> }
> ```

And the error is :

> First-chance exception: core.exception.RangeError Range violation at source\ml\media\TilemapManager.d(138)

I used these as a wrapper for storing the objects:

```
private Object_Layer_Data[string] object_list;
```

> struct Object_Layer_Data
> {
>     ObjectData[] object_;
> }

and I did insert it into the struct:

```
object_list[name] = Object_Layer_Data(data.getLayer("object").objects);
```

**Comment by rcorre** [comment]
Sorry, to be honest I have no idea. I guess try `assert(name in object_list)` before running your loop.

**Comment by Jackoz530** [comment]
> Sorry, to be honest I have no idea. I guess try assert(name in object_list) before running your loop.

I'll try it. I'll continue to explore and experiment for solutions. If I find one I'll post it here.
Please keep this issue open until then.

**Comment by Jackoz530** [comment]
Turns out I was accessing a null array in the code. Assert helped me find the bug. Closing this now.
Thank you.

**Comment by rcorre** [comment]
Glad you got it figured out.
To make it easier to discuss things that aren't bugs, I created a [Gitter chat room](https://gitter.im/rcorre/dtiled) for this repo.

I've never used Gitter before but it should be useful for discussing and getting help with things that are not necessarily bugs. Of course, if something _does_ seem like a bug with dtiled, definitely report it :)
